version: 0.2

phases:
  install:
    commands:
      - echo Installing all NPM Dependencies Chris
      - npm install

  build:
    commands:
      - npm run build
      - echo Build completed
artifacts:
  files:
    - "**/*"
  base-directory: dist
  discard-paths: no
